### ISSUE TITLE
모듈화

### ISSUE THREAD

**Issue by WOPH96** [WOPH96/SSD_Project#26]
동수의 
test_shell.cpp와 Ctrl_SSD.cpp를
header와 cpp로 나누고,

1. header와 source를 합쳐서 컴파일 + 빌드 할 수 있도록 Makefile 만들기

동수의 업데이트 전까지 Ctrl_SSD.cpp를 나누고 빌드하는 것을 목표로

**Comment by JunWon11** [comment]
완료했습니다.
