### ISSUE TITLE
memory.bin 파일 만들기

### ISSUE THREAD

**Issue by WOPH96** [WOPH96/SSD_Project#5]
Virtual SSD -> memory.bin 파일 

400byte의 메모리 만들어야 함.

**Comment by WOPH96** [comment]
Read 명령어와 Write 명령어만 존재
 LBA 단위는 4 Byte • LBA 0 ~ 99 까지 100 칸을 저장할 수 있다.

**Comment by DongsuHan12** [comment]
한동수 담당
